$(function(){
    $("img").hover(
        function(){
        $(this).animate({width:"150px",
                         height:"150px",
                         marginTop:"-30px"});
    },function(){
        $(this).animate({width:"100px",
                height:"100px",
                marginTop:"0px"
        });
    }              
 );
});